### ISSUE TITLE
Example is needed

### ISSUE THREAD

**Issue by halvardos** [gilly3/lazy-json-viewer#1]
Hey, an example of how this looks. Just a screenshot would be nice :)

**Comment by gilly3** [comment]
How about a live demo?  http://gilly3.com/ljv/

**Comment by halvardos** [comment]
I must be completely blind. Sorry! :D

**Comment by gilly3** [comment]
You're not blind, I added it just now.  I added a screenshot to the readme as well.

**Comment by halvardos** [comment]
hehehe, i went back to the readme and found it. So i though i just overlooked it completely the first time :)

Thank you.
